apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-services
  namespace: my-service
  labels:
    app: my-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-services
  template:
    metadata:
      labels:
        app: my-services
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "my-service"
        vault.hashicorp.com/vault-address: "http://host.minikube.internal:8200"

        # ðŸ”‘ Vault injeta ENV diretamente
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/my-service"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/my-service" -}}
          {{- range $k, $v := .Data.data }}
          {{ $k }}={{ $v }}
          {{- end }}
          {{- end }}

    spec:
      serviceAccountName: my-service-sa
      terminationGracePeriodSeconds: 5

      containers:
        - name: my-services
          image: my-services:0.1
          imagePullPolicy: IfNotPresent

          # ðŸš« SEM command / args
          # Dockerfile continua mandando

          ports:
            - containerPort: 9999
              name: http

          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
            initialDelaySeconds: 30
            periodSeconds: 15
