apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-services-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: myservices.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-services
                port:
                  number: 80
