apiVersion: v1
kind: Service
metadata:
  name: my-services
spec:
  type: ClusterIP
  selector:
    app: my-services
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9999
